require('./index.less');

//require('./src/bind');
//require('./src/ajax_promise');
//require('./src/throttle_debounce');
//require('./src/unique_array');
//require('./src/object_create');
//require('./src/json_stringify');
//require('./src/chunk');
//require('./src/recursion');
//require('./src/pubsub');
//require('./src/tagged_template');
//require('./src/sort.js');
//require('./src/imp_req');
//require('./src/reg_exp');
//require('./src/run_script');
//require('./src/js_besides_js');
//require('./src/least_num');
//require('./src/deep_copy');
